filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/host_logs/*.log
    multiline.pattern: '^[ \t]' # json 형식도 다 가져올 수 있도록
    multiline.negate: false
    multiline.match: after

output.logstash:
  hosts: ["logstash:5044"]
