package org.example.pdnight.global.common.enums;

public enum JobCategory {
    BACK_END_DEVELOPER,
    FRONT_END_DEVELOPER,
    FULL_STACK_DEVELOPER,
    MOBILE_DEVELOPER,
    DEVOPS_ENGINEER,
    DATA_ENGINEER,
    DATA_SCIENTIST,
    MACHINE_LEARNING_ENGINEER,
    AI_RESEARCHER,
    PROJECT_MANAGER,
    PRODUCT_MANAGER,
    DESIGNER,
    QA_ENGINEER,
    SECURITY_ENGINEER,
    SYSTEM_ENGINEER,
    GAME_DEVELOPER,
    EMBEDDED_ENGINEER,
    ETC, // 기타
    ALL
}
